### ISSUE TITLE
Subscription checks very complicated

### ISSUE THREAD

**Issue by tbludau** [rhmk/ansible-hana-examples#19]
Need three roles:
Self-Configured integration
Satellite 6 Integration
subscription-manager integratation

Checks:
Check if packages available from needed repositorys.

For Demo Scenario:
Use RedHat Login as variable
execute following commands (example):
subscription-manager clean
subscription-manager remove --all
subscription-manager register
rm -rf /etc/yum.repos.d/*
rm -fr /var/cache/yum/*
yum clean all 
# subscription-manager list --available --all
subscription-manager attach --pool=xxx
subscription-manager release --set=7.2
subscription-manager repos --disable=rhel-7-server-rpms
subscription-manager repos --enable=rhel-7-server-eus-rpms
# Deltarpm is necessary for the following rpm installation ?!?!
yum install -y deltarpm

**Comment by kyleabenson** [comment]
@tbludau There is some good work that can be done here.. Both in specific tasks and structure.

Many of these tasks where the `shell` or `command` modules are being used for subscriptions can be remediated using either the `redhat_subscription` or `yum_repository` modules.

As far as structure we should be able to reduce some of these plays by enforcing a desired state around subscriptions rather than doing checking like so:

```yaml
- name: Reset all previous repositories
  shell: |
    subscription-manager repos --disable="*"
    num=0
    for r in /etc/yum.repos.d/*.repo; do
      num=$(( num + $(grep  -c "^enabled.*=.*1$" $r) ))
      sed -i 's/^enabled.*=.*1/enabled = 0/g' $r
    done
    echo "$num"
  register: repo_cleanup
  changed_when: repo_cleanup.stdout > 0
  failed_when: repo_cleanup.rc > 0
  when: force_repo_reset
```

We shouldn't need to do loops in tasks for each repo, the `yum_repository` module should be able to disable all repos. We should also try to get to a state with this role assuming that we either want to force a repo reset every time or not before this task. 

If there are instances where the answer is 'it depends' we should try to be more selective in resolving repo conflicts

Lastly, I think we can restructure the suggest roles into either 'self-configured' or 'subscription-based'. We should be able to perform a couple of tasks based on wether a Sat 6 URL var is present or not, then proceed as normal.

Thoughts?

**Comment by kyleabenson** [comment]
@tbludau I think we can close this task -- there is a lot of cleanup to be done in issue #13 so I can resolve some of these.

**Comment by kyleabenson** [comment]
@tbludau question..  are we setting a strict level on ansible version? There's currently a new rhsm_repository module in the development stream for ansible 2.5 that might clean up some of this too.

**Comment by tbludau** [comment]
hey @kyleabenson thanks for your input and sorry for my delayed response. as you descibed we can close this case, because it should not be part of the ansible deployment and brings a lot of erros in aws and azure environments.
